workspace:
  base: /code

pipeline:
  publish-staging-build:
    image: plugins/docker
    repo: nossas/bonde
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    group: builder
    tags:
      - builder
    when:
      status: success
      event: [push]

  publish-production-build:
    image: plugins/docker
    repo: nossas/bonde
    dockerfile: Dockerfile.production
    secrets: [ docker_username, docker_password ]
    group: builder
    tags:
      - builder-prod
    when:
      status: success
      event: tag

  publish-accounts:
    image: plugins/docker
    repo: nossas/bonde
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/accounts-client/Dockerfile
    context: packages/accounts-client/
    group: clients
    tags:
      - accounts
    when:
      status: success
      event: [push]

  publish-canary:
    image: plugins/docker
    repo: nossas/bonde
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/canary-client/Dockerfile
    context: packages/canary-client/
    group: clients
    tags:
      - canary
    when:
      status: success
      event: [push]

  publish-redes:
    image: plugins/docker
    repo: nossas/bonde
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/redes-client/Dockerfile
    context: packages/redes-client/
    group: clients
    tags:
      - redes
    when:
      status: success
      event: [push]

  accounts-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: clients/accounts
    group: deploying
    docker_image: nossas/bonde:accounts
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  canary-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: clients/canary
    group: deploying
    docker_image: nossas/bonde:canary
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  redes-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/redes
    group: deploying
    docker_image: nossas/bonde:redes
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: [push]

  publish-accounts-prod:
    image: plugins/docker
    repo: nossas/bonde
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/accounts-client/Dockerfile.production
    context: packages/accounts-client/
    group: clients
    tags:
      - accounts-prod
    when:
      status: success
      event: tag

  publish-canary-prod:
    image: plugins/docker
    repo: nossas/bonde
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/canary-client/Dockerfile.production
    context: packages/canary-client/
    group: clients
    tags:
      - canary-prod
    when:
      status: success
      event: tag
