workspace:
  base: /code

pipeline:
  tests:
    image: node:16-alpine
    commands:
      - apk --update add curl
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
      - cd monorepo
      - pnpm i
      - pnpm m run test:coverage

  coverage:
    image: plugins/codecov
    secrets: [codecov_token]
    paths:
      - packages/**/coverage
      - libs/**/coverage

  build:
    image: node:16-alpine
    commands:
      - apk --update add curl
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
      - cd monorepo
      - pnpm i
      - pnpm m run build