pipeline:
  build:
    image: kkarczmarczyk/node-yarn
    commands:
      - yarn
      - yarn test
    when:
      event: [push, tag]

  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-client
    username: lpirola
    password: ${DOCKER_PASSWORD}
    tags:
      - ${DRONE_BRANCH}
    build_args:
      - PAGARME_KEY=${STAG_PAGARME_KEY}
      - GOOGLE_FONTS_API_KEY=${STAG_GOOGLE_FONTS_API_KEY}
      - AWS_ACCESS_KEY_ID=${STAG_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${STAG_AWS_SECRET_ACCESS_KEY}
      - SENTRY_DSN_PUBLIC=${STAG_SENTRY_DSN_PUBLIC}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-staging:
    image: appleboy/drone-ssh
    host: staging.bonde.org
    username: ubuntu
    command_timeout: 120
    port: 22
    script:
      - sudo docker pull nossas/bonde-client:${DRONE_BRANCH}
      - sudo docker tag nossas/bonde-client:${DRONE_BRANCH} dokku/0-client:latest
      - dokku tags:deploy 0-client latest
      - dokku tags:deploy app-client latest
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-production:
    image: plugins/docker
    repo: nossas/bonde-client
    username: lpirola
    password: ${DOCKER_PASSWORD}
    tags:
      - ${DRONE_TAG##v}
    build_args:
      - NODE_ENV=production
      - PAGARME_KEY=${PROD_PAGARME_KEY}
      - GOOGLE_FONTS_API_KEY=${PROD_GOOGLE_FONTS_API_KEY}
      - APP_DOMAIN=bonde.org
      - API_URL=https://api.bonde.org
      - AWS_BUCKET=bonde-assets
      - AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
      - SENTRY_DSN_PUBLIC=${PROD_SENTRY_DSN_PUBLIC}
    when:
      status: success
      event: tag

  deploy-production:
    image: appleboy/drone-ssh
    host: bonde.org
    username: ubuntu
    command_timeout: 120
    port: 22
    script:
      - sudo docker pull nossas/bonde-client:${DRONE_TAG##v}
      - sudo docker tag nossas/bonde-client:${DRONE_TAG##v} dokku/0-client:latest
      - sudo docker tag nossas/bonde-client:${DRONE_TAG##v} dokku/app-client:latest
      - dokku tags:deploy 0-client latest
      - dokku tags:deploy app-client latest
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
