workspace:
  base: /code

pipeline:
  build:
    image: debian:10-slim
    environment:
      - REACT_APP_ENVIRONMENT=staging
      - REACT_APP_DOMAIN_ACCOUNTS=https://accounts.staging.bonde.org
      - REACT_APP_DOMAIN_ADMIN=https://app.staging.bonde.org
      - REACT_APP_DOMAIN_ADMIN_CANARY=https://admin-canary.staging.bonde.org
      - REACT_APP_DOMAIN_PUBLIC=staging.bonde.org
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.staging.bonde.org
      - REACT_APP_DOMAIN_API_REST=https://api-rest.staging.bonde.org
      - REACT_APP_DOMAIN_API_GRAPHQL=https://api-graphql.staging.bonde.org/v1/graphql
      - REACT_APP_HASURA_API_URL=https://api-graphql.staging.bonde.org/v1/graphql
      - REACT_APP_DOMAIN_BOT=https://chatbot.staging.bonde.org
      - REACT_APP_DOMAIN_BETA=https://beta.staging.bonde.org
      - REACT_APP_AWS_BUCKET=bonde-assets-staging
      - REACT_APP_LOGIN_URL=https://accounts.staging.bonde.org/login
      - REACT_APP_DOMAIN_REDES=https://redes.staging.bonde.org
      - REACT_APP_UPLOADS_URL=http://api-rest.staging.bonde.org/uploads
      - REACT_APP_ZENDESK_ORGANIZATIONS={"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}
    commands:
      - export REACT_APP_AWS_ROUTE_IP=$AWS_ROUTE_IP
      - export WAYPOINT_SERVER_ADDR=cluster-k8s.nossas.org:9701
      - export WAYPOINT_SERVER_TLS=1
      - export WAYPOINT_SERVER_TLS_SKIP_VERIFY=1
      - export WAYPOINT_SERVER_TOKEN=$WAYPOINT_SERVER_TOKEN
      - apt-get update && apt-get install -y curl gnupg2 software-properties-common
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com buster main"
      - apt-get update && apt-get install -y waypoint
      - waypoint init
      - waypoint build
    secrets: [ aws_route_ip, waypoint_server_token ]
    group: build
    when:
      status: success
      event: [push]

  production-build:
    image: node:14-alpine
    environment:
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_DOMAIN_ACCOUNTS=https://accounts.bonde.org
      - REACT_APP_DOMAIN_ADMIN=https://app.bonde.org
      - REACT_APP_DOMAIN_ADMIN_CANARY=https://admin-canary.bonde.org
      - REACT_APP_DOMAIN_PUBLIC=bonde.org
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.bonde.org
      - REACT_APP_DOMAIN_API_REST=https://api-rest.bonde.org
      - REACT_APP_DOMAIN_API_GRAPHQL=https://api-graphql.bonde.org/v1/graphql
      - REACT_APP_HASURA_API_URL=https://api-graphql.bonde.org/v1/graphql
      - REACT_APP_DOMAIN_BOT=https://chatbot.bonde.org
      - REACT_APP_DOMAIN_BETA=https://beta.bonde.org
      - REACT_APP_AWS_BUCKET=bonde-assets
      - REACT_APP_LOGIN_URL=https://accounts.bonde.org/login
      - REACT_APP_DOMAIN_REDES=https://redes.bonde.org
      - REACT_APP_UPLOADS_URL=http://api-rest.bonde.org/uploads
      - REACT_APP_ZENDESK_ORGANIZATIONS={"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}
    commands:
      - apk --update add curl
      - curl -L https://unpkg.com/@pnpm/self-installer | node
      - export REACT_APP_AWS_ROUTE_IP=$AWS_ROUTE_IP
      - pnpm i
      - pnpm m run build
    secrets: [ aws_route_ip ]
    group: build
    when:
      status: success
      event: tag

  # publish-staging-build:
  #   image: plugins/docker
  #   repo: nossas/bonde
  #   dockerfile: Dockerfile
  #   secrets: [docker_username, docker_password]
  #   group: publish
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     event: [push]

  publish-production-build:
    image: plugins/docker
    repo: nossas/bonde
    dockerfile: Dockerfile
    secrets: [docker_username, docker_password]
    group: publish
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag

  accounts-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: clients/accounts
    group: deploying
    docker_image: nossas/bonde:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      event: [push]

  canary-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: clients/canary
    group: deploying
    docker_image: nossas/bonde:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      event: [push]

  redes-staging-deploy:
    image: debian:10-slim
    commands:
      - export WAYPOINT_SERVER_ADDR=cluster-k8s.nossas.org:9701
      - export WAYPOINT_SERVER_TLS=1
      - export WAYPOINT_SERVER_TLS_SKIP_VERIFY=1
      - export WAYPOINT_SERVER_TOKEN=$WAYPOINT_SERVER_TOKEN
      - apt-get update && apt-get install -y curl gnupg2 software-properties-common
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com buster main"
      - apt-get update && apt-get install -y waypoint
      - waypoint build
    group: deploying
    secrets: [waypoint_server_token]
    commands:
      - waypoint up
    when:
      status: success
      event: [push]

  redes-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: clients/redes
    group: deploying
    docker_image: nossas/bonde:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag
