workspace:
  base: /code

pipeline:
  tests:
    image: node:16-alpine
    commands:
      - apk --update add curl
      - curl -L https://unpkg.com/@pnpm/self-installer | node
      - cd monorepo
      - pnpm i
      - pnpm m run test
      - pnpm m run test:coverage
  build:
    image: node:16-alpine
    commands:
      - apk --update add curl
      - curl -L https://unpkg.com/@pnpm/self-installer | node
      - cd monorepo
      - pnpm i
      - pnpm m run build