version: "3.7"
services:
  builder:
    image: nossas/bonde:builder
    build: .
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_DOMAIN_ADMIN=http://app.bonde.devel:4001
      - REACT_APP_DOMAIN_ADMIN_CANARY=http://admin-canary.bonde.devel:4002
      - REACT_APP_DOMAIN_PUBLIC=staging.bonde.org
      - REACT_APP_DOMAIN_CROSS_STORAGE=http://cross-storage.bonde.devel
      - REACT_APP_DOMAIN_API_REST=https://api-rest.staging.bonde.org
      - REACT_APP_DOMAIN_API_GRAPHQL=https://api-graphql.staging.bonde.org/v1/graphql
      - REACT_APP_DOMAIN_BOT=https://chatbot.staging.bonde.org
      - REACT_APP_DOMAIN_BETA=https://beta.staging.bonde.org
      - REACT_APP_AWS_BUCKET=bonde-assets-staging
      - REACT_APP_LOGIN_URL=http://accounts.bonde.devel:4000/login
      - REACT_APP_DOMAIN_REDES=https://redes.staging.bonde.org

  traefik:
    image: traefik:1.7-alpine
    environment:
      AWS_ACCESS_KEY_ID: xxxxxxx
      AWS_SECRET_ACCESS_KEY: xxxxxx
      AWS_REGION: us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/traefik.toml"
    ports:
    - 80:80/tcp
    - 8080:8080/tcp
    - 443:443/tcp
    command:
    - --configfile=/traefik.toml
    labels:
      traefik.frontend.rule: Host:traefik.bonde.devel
      traefik.alias: traefik
      traefik.port: '8080'
      traefik.enable: 'true'
  
  cross-storage:
    image: nossas/bonde-cross-storage:feature-devel
    # build: ../bonde-cross-storage
    ports:
      - "8888:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    labels:
      traefik.frontend.rule: Host:cross-storage.bonde.devel
      traefik.enable: 'true'
      traefik.alias: cross-storage
      traefik.port: '80'

  accounts:
    # build: packages/accounts-client
    image: nossas/bonde:feature-upload-image
    command: yarn pnpm m run start --filter accounts-client
    ports:
      - "5000:5000"
    labels:
      traefik.frontend.rule: Host:accounts.bonde.devel
      traefik.enable: 'true'
      traefik.alias: accounts
      traefik.port: '5000'