packages:
  # all packages in subdirs of packages/ and components/
  - '.'
  - './libs/components'
  - './libs/core-tools'
  - './libs/webpage'
  - '!./packages/example-client'
  - './packages/*'
  # - '!packages/example-client'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
