packages:
  # all packages in subdirs of packages/ and components/
  - '.'
  - 'packages/*'
  - 'libs/core-tools'
  - 'libs/components'
  - '!packages/example-client'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
