name: Reusable tests for apps
on:
  workflow_call:

jobs:
  tests:
    runs-on: self-hosted 
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: cd clients && pnpm i

      - name: Run tests
        run: cd clients && pnpm test
        env:
          REACT_APP_DOMAIN_API_GRAPHQL: http://localhost:3000
          DISABLE_MOCKED_WARNING: true

      - name: Map webpage hostname
        run: sudo echo "127.0.0.1 testes-de-widgets-com-cypress.bonde.devel" | sudo tee -a /etc/hosts

      - name: Run e2e tests
        run: cd clients && pnpm --filter webpage-client m run build && pnpm --filter webpage-client m run e2e:headless
        env:
          REACT_APP_DOMAIN_API_GRAPHQL: https://api-graphql.staging.bonde.org/v1/graphql

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: ./clients/coverage
          flags: unittests
          verbose: true
